FROM ubuntu:24.04

RUN set -xe; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        tzdata; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        make \
        unzip \
        wget \
        zip; \
    rm -rf /var/lib/apt/lists/*
